ComponentConfig:
  version: 1.0.0
  type: 核心依赖
  uid: component-config
  operation: false
  menu:
    label: 插件装载
    key: go-to-component
    path: /component
  router:
    path: /component
    name: Component
    component: /src/views/componentConfig/ComponentConfig.vue
  isNeedVerify: true
