# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpcService/sysInfo.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'grpcService/sysInfo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19grpcService/sysInfo.proto\x12\x07sysInfo\"\x0c\n\nCpuRequest\"\x19\n\x08\x43puReply\x12\r\n\x05usage\x18\x01 \x01(\x02\"\x0f\n\rMemoryRequest\"9\n\x0bMemoryReply\x12\r\n\x05usage\x18\x01 \x01(\x05\x12\r\n\x05total\x18\x02 \x01(\x05\x12\x0c\n\x04used\x18\x03 \x01(\x05\"\x10\n\x0eSysInfoRequest\"O\n\x07\x43puInfo\x12\x0f\n\x07\x63puName\x18\x01 \x01(\t\x12\x0f\n\x07\x63puCore\x18\x02 \x01(\x05\x12\x11\n\tcpuThread\x18\x03 \x01(\x05\x12\x0f\n\x07\x63puFreq\x18\x04 \x01(\x02\"!\n\nMemoryInfo\x12\x13\n\x0bmemoryTotal\x18\x01 \x01(\x02\"f\n\x0cSysInfoReply\x12!\n\x07\x63puInfo\x18\x01 \x01(\x0b\x32\x10.sysInfo.CpuInfo\x12\'\n\nmemoryInfo\x18\x02 \x01(\x0b\x32\x13.sysInfo.MemoryInfo\x1a\n\n\x08\x64iskInfo2\x8e\x01\n\x0eSysInfoService\x12\x38\n\ncpuService\x12\x13.sysInfo.CpuRequest\x1a\x11.sysInfo.CpuReply\"\x00\x30\x01\x12\x42\n\x0esysInfoService\x12\x17.sysInfo.SysInfoRequest\x1a\x15.sysInfo.SysInfoReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpcService.sysInfo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CPUREQUEST']._serialized_start=38
  _globals['_CPUREQUEST']._serialized_end=50
  _globals['_CPUREPLY']._serialized_start=52
  _globals['_CPUREPLY']._serialized_end=77
  _globals['_MEMORYREQUEST']._serialized_start=79
  _globals['_MEMORYREQUEST']._serialized_end=94
  _globals['_MEMORYREPLY']._serialized_start=96
  _globals['_MEMORYREPLY']._serialized_end=153
  _globals['_SYSINFOREQUEST']._serialized_start=155
  _globals['_SYSINFOREQUEST']._serialized_end=171
  _globals['_CPUINFO']._serialized_start=173
  _globals['_CPUINFO']._serialized_end=252
  _globals['_MEMORYINFO']._serialized_start=254
  _globals['_MEMORYINFO']._serialized_end=287
  _globals['_SYSINFOREPLY']._serialized_start=289
  _globals['_SYSINFOREPLY']._serialized_end=391
  _globals['_SYSINFOREPLY_DISKINFO']._serialized_start=381
  _globals['_SYSINFOREPLY_DISKINFO']._serialized_end=391
  _globals['_SYSINFOSERVICE']._serialized_start=394
  _globals['_SYSINFOSERVICE']._serialized_end=536
# @@protoc_insertion_point(module_scope)
