# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from grpcService import sysInfo_pb2 as grpcService_dot_sysInfo__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in grpcService/sysInfo_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SysInfoServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.cpuService = channel.unary_stream(
                '/sysInfo.SysInfoService/cpuService',
                request_serializer=grpcService_dot_sysInfo__pb2.CpuRequest.SerializeToString,
                response_deserializer=grpcService_dot_sysInfo__pb2.CpuReply.FromString,
                _registered_method=True)
        self.sysInfoService = channel.unary_unary(
                '/sysInfo.SysInfoService/sysInfoService',
                request_serializer=grpcService_dot_sysInfo__pb2.SysInfoRequest.SerializeToString,
                response_deserializer=grpcService_dot_sysInfo__pb2.SysInfoReply.FromString,
                _registered_method=True)


class SysInfoServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def cpuService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def sysInfoService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SysInfoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'cpuService': grpc.unary_stream_rpc_method_handler(
                    servicer.cpuService,
                    request_deserializer=grpcService_dot_sysInfo__pb2.CpuRequest.FromString,
                    response_serializer=grpcService_dot_sysInfo__pb2.CpuReply.SerializeToString,
            ),
            'sysInfoService': grpc.unary_unary_rpc_method_handler(
                    servicer.sysInfoService,
                    request_deserializer=grpcService_dot_sysInfo__pb2.SysInfoRequest.FromString,
                    response_serializer=grpcService_dot_sysInfo__pb2.SysInfoReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sysInfo.SysInfoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sysInfo.SysInfoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SysInfoService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def cpuService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/sysInfo.SysInfoService/cpuService',
            grpcService_dot_sysInfo__pb2.CpuRequest.SerializeToString,
            grpcService_dot_sysInfo__pb2.CpuReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def sysInfoService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sysInfo.SysInfoService/sysInfoService',
            grpcService_dot_sysInfo__pb2.SysInfoRequest.SerializeToString,
            grpcService_dot_sysInfo__pb2.SysInfoReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
